package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Appuser generated by hbm2java
 */
public class Appuser  implements java.io.Serializable {


     private AppuserId id;
     private String description;

    public Appuser() {
    }

    public Appuser(AppuserId id, String description) {
       this.id = id;
       this.description = description;
    }
   
    public AppuserId getId() {
        return this.id;
    }
    
    public void setId(AppuserId id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


