package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Deviceregister generated by hbm2java
 */
public class Deviceregister  implements java.io.Serializable {


     private int id;
     private String deviceUdid;
     private String appId;
     private String userId;
     private String deviceToken;
     private String appVersion;

    public Deviceregister() {
    }

    public Deviceregister(int id, String deviceUdid, String appId, String userId, String deviceToken, String appVersion) {
       this.id = id;
       this.deviceUdid = deviceUdid;
       this.appId = appId;
       this.userId = userId;
       this.deviceToken = deviceToken;
       this.appVersion = appVersion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDeviceUdid() {
        return this.deviceUdid;
    }
    
    public void setDeviceUdid(String deviceUdid) {
        this.deviceUdid = deviceUdid;
    }
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getDeviceToken() {
        return this.deviceToken;
    }
    
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }
    public String getAppVersion() {
        return this.appVersion;
    }
    
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }




}


