package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private String groupId;
     private String groupName;
     private String description;

    public Group() {
    }

    public Group(String groupId, String groupName, String description) {
       this.groupId = groupId;
       this.groupName = groupName;
       this.description = description;
    }
   
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


