package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private LogId id;
     private String messageLog;
     private Date timeLog;
     private String appId;

    public Log() {
    }

    public Log(LogId id, String messageLog, Date timeLog, String appId) {
       this.id = id;
       this.messageLog = messageLog;
       this.timeLog = timeLog;
       this.appId = appId;
    }
   
    public LogId getId() {
        return this.id;
    }
    
    public void setId(LogId id) {
        this.id = id;
    }
    public String getMessageLog() {
        return this.messageLog;
    }
    
    public void setMessageLog(String messageLog) {
        this.messageLog = messageLog;
    }
    public Date getTimeLog() {
        return this.timeLog;
    }
    
    public void setTimeLog(Date timeLog) {
        this.timeLog = timeLog;
    }
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }




}


