package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * MessagesentId generated by hbm2java
 */
public class MessagesentId  implements java.io.Serializable {


     private String messageId;
     private String userId;

    public MessagesentId() {
    }

    public MessagesentId(String messageId, String userId) {
       this.messageId = messageId;
       this.userId = userId;
    }
   
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MessagesentId) ) return false;
		 MessagesentId castOther = ( MessagesentId ) other; 
         
		 return ( (this.getMessageId()==castOther.getMessageId()) || ( this.getMessageId()!=null && castOther.getMessageId()!=null && this.getMessageId().equals(castOther.getMessageId()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMessageId() == null ? 0 : this.getMessageId().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   


}


