package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Messagesent generated by hbm2java
 */
public class Messagesent  implements java.io.Serializable {


     private MessagesentId id;
     private int status;

    public Messagesent() {
    }

    public Messagesent(MessagesentId id, int status) {
       this.id = id;
       this.status = status;
    }
   
    public MessagesentId getId() {
        return this.id;
    }
    
    public void setId(MessagesentId id) {
        this.id = id;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


