package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private String roleId;
     private String roleName;
     private String description;

    public Role() {
    }

    public Role(String roleId, String roleName, String description) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.description = description;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


