package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Userdata generated by hbm2java
 */
public class Userdata  implements java.io.Serializable {


     private int id;
     private String databaseName;
     private String userId;
     private String appId;
     private int appVersion;
     private String schemXml;

    public Userdata() {
    }

    public Userdata(int id, String databaseName, String userId, String appId, int appVersion, String schemXml) {
       this.id = id;
       this.databaseName = databaseName;
       this.userId = userId;
       this.appId = appId;
       this.appVersion = appVersion;
       this.schemXml = schemXml;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDatabaseName() {
        return this.databaseName;
    }
    
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getAppId() {
        return this.appId;
    }
    
    public void setAppId(String appId) {
        this.appId = appId;
    }
    public int getAppVersion() {
        return this.appVersion;
    }
    
    public void setAppVersion(int appVersion) {
        this.appVersion = appVersion;
    }
    public String getSchemXml() {
        return this.schemXml;
    }
    
    public void setSchemXml(String schemXml) {
        this.schemXml = schemXml;
    }




}


