package Entities;
// Generated Aug 14, 2013 9:29:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Usergroupdetail generated by hbm2java
 */
public class Usergroupdetail  implements java.io.Serializable {


     private UsergroupdetailId id;

    public Usergroupdetail() {
    }

    public Usergroupdetail(UsergroupdetailId id) {
       this.id = id;
    }
   
    public UsergroupdetailId getId() {
        return this.id;
    }
    
    public void setId(UsergroupdetailId id) {
        this.id = id;
    }




}


